import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { Box, ThemeProvider } from '@mui/material';
import { theme } from '@/theme';
import '../styles/reset.css';

export const metadata: Metadata = {
  title: 'Desafio 2 - Posts',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            <Box
              sx={{
                width: '100vw',
                height: '100vh',
                bgcolor: 'background.default',
                color: 'text.primary',
              }}
            >
              {children}
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
